language: python
python:
  - "3.6"
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m textblob.download_corpora
# command to run tests
script:
  - pytest